exports.getLatestInfo = require('./getLatestInfo')
exports.getTrendingInfo = require('./getTrendingInfo')
exports.getQueryInfo = require('./getQueryInfo')
exports.help = require('./help')
exports.root = require('./root')